# Usar una imagen base de Python
FROM python:3.9-slim

# Establecer un directorio de trabajo
WORKDIR /app

# Copiar los archivos del proyecto al contenedor
COPY . /app/

# Instalar las dependencias
RUN pip install -r requirements.txt

# Generar los archivos gRPC
RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. hello.proto

# Establecer el comando por defecto para ejecutar el servidor
CMD ["python", "hello_server.py"]